name: Deploy to FTP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        # Here is the deployment action
        - name: 🚀 Upload from public_html via FTP
          uses: airvzxf/ftp-deployment-action@latest
          with:
            server: ftp.magaliechetrit.com
            user: ftp@magaliechetrit.com
            password: ${{ secrets.FTPPASSWORD }}
            local_dir: ./output/
            remote_dir: /magaliechetrit.com/public_html/
